### ISSUE TITLE
로그 파일명 분리

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#1]
기능 정의서상에서 시스템 로그가 2가지 존재하지만 각각 어느 로그인지 알수 없음.
* 각각의 로그를 별도의 파일명을 가지게 하는 방법
* 각각의 로그를 별도의 디렉토리에 넣는 방법도 좋을 것으로 보임
  * 운영 및 동작 상태 로그 파일 : ex)System\yyyy-mm-dd.log
  * 검지 이력 로그 파일 : ex)Detection\yyyy-mm-dd.log

**Comment by small-b** [comment]
아래와 같이 소스 수정 완료.
운영 및 동작 상태 로그 : log\System 폴더 하위에 적재
검지 이력 로그 : log\Detection 폴더 하위에 적재

**Comment by small-b** [comment]
아래와 같이 소스 수정 완료.
운영 및 동작 상태 로그 : log\System 폴더 하위에 적재
검지 이력 로그 : log\Detection 폴더 하위에 적재
