### ISSUE TITLE
윈도우 View 제어창의 체크

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#10]
* 개별 윈도우에서 우측 상단의 X를 이용하여 윈도우를 닫을 경우
 * 윈도우 제어창에서 실제 체크해제시 윈도우가 보이게됨
 * 단순 토글로 구현되었기 때문인듯함.
![window_viewctrl](https://cloud.githubusercontent.com/assets/1232645/18299612/31d5954a-74fd-11e6-9c87-835cd3bd6679.png)

**Comment by small-b** [comment]
수정완료.

**Comment by Miragecore** [comment]
![image](https://cloud.githubusercontent.com/assets/1232645/18422143/c734f3ce-78d1-11e6-8c30-149b1e304623.png)
1. 위의 X 표시를 이용하여 창을 닫습니다.
![image](https://cloud.githubusercontent.com/assets/1232645/18422169/fd9d33c2-78d1-11e6-8e9d-84b929fab575.png)
2. 레이더 리스트창은 사라졌지만 여전히 View 컨트롤에서는 체크가 되어있습니다.
3. 그래서 체크를 해제해봅니다. 
![image](https://cloud.githubusercontent.com/assets/1232645/18422189/464b71d8-78d2-11e6-92a3-137e32d6e505.png)
4. 해제하면 레이더 리스트가 등장합니다.

**Comment by small-b** [comment]
수정하였습니다.

**Comment by Miragecore** [comment]
* 확인 완료
