### ISSUE TITLE
CCTV 그룹 관리 기능 없음

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#12]
* CCTV를 제어하는 기능은 있으나 CCTV를 추가하거나 수정 삭제하는 기능은 없음

**Comment by small-b** [comment]
* 레이더 리스트 화면에서 레이더 명칭 우측에 CCTV 버튼을 추가함.
* CCTV 버튼(토글)로 CCTV 리스트 표시/감추기 기능을 수행
* CCTV 리스트가 표시되면, 추가/수정/삭제 가능.

**Comment by Miragecore** [comment]
![image](https://cloud.githubusercontent.com/assets/1232645/18422032/7fd78fce-78d0-11e6-8e0d-f859b70ae8bf.png)
* CCTV 추가 삭제시 이름없이 추가 삭제 가능
 * 이름이 없는데 Edit창에서 선택이 가능하니 이상한듯 합니다.

**Comment by small-b** [comment]
>> CCTV 이름없이 추가 및 수정되지 않도록 하였습니다.

**Comment by Miragecore** [comment]
* 실제 CCTV 연결후 확인후 Close하겠습니다.

**Comment by Miragecore** [comment]
* 이슈 #29 픽스 필요
