### ISSUE TITLE
환경 설정 상단 시스템 상태 표현

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#13]
![image](https://cloud.githubusercontent.com/assets/1232645/18415737/ad639634-7837-11e6-9604-08e5123a5870.png)

* 환경 설정 상단의 제어부 상태 및 센서부 상태 표시가 되도록 할 필요가 있을 듯함.
 * 에뮬레이터 상에서 프로토콜로 데이터를 전달
 * 에뮬레이터상에서 해당 내용이 보여야 할 것으로 생각됨.

**Comment by small-b** [comment]
해당 기능 구현함.
(프로토콜 상, 30초 이내에 업데이트 됨.)

**Comment by Miragecore** [comment]
* 센서부 상태도 뭔가 표시되면 좋을듯 합니다!

**Comment by small-b** [comment]
>> 센서부는 모두 정상으로 표시되도록 하였습니다.

**Comment by Miragecore** [comment]
![image](https://cloud.githubusercontent.com/assets/1232645/18612780/23317456-7d9e-11e6-854b-aae5823faced.png)
* 위와 같이 글자가 짤려서 안 보이는 부분은 지적될 가능성이 있습니다.
* 텍스트 박스를 좀 더 키우시죠.
