### ISSUE TITLE
환경 설정

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#14]
* 환경 설정창의 데이터가 제대로 반영되었는지를 확인할 방법이 필요
 * 에뮬레이터상에서 환경 설정창과 동일한 방법으로 디스플레이가 좋을 듯함.

**Comment by small-b** [comment]
>> 에뮬레이터에 정보 표시 창을 추가하였습니다.

**Comment by Miragecore** [comment]
이슈 #28 [https://github.com/WorkForGS/ToBeNice/issues/28](url) 픽스 필요
