### ISSUE TITLE
환경설정>추적 카메라 속성 동작 여부

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#15]
![image](https://cloud.githubusercontent.com/assets/1232645/18415746/352126ea-7838-11e6-8dfb-c03b81b25ecb.png)

위의 그림의 추적 카메라 위치 확인 하는 것이 동작하는 것인지요?
동작하지 않는 기능이라면 없애는 것이 좋을 것으로 판단됨.

동작하는 기능이라면 현재 PAN 값만 있고 Tilt를 표현해주는 값이 없음.

**Comment by small-b** [comment]
추적카메라 및 추적카메라 PTZ 탭은 삭제함.

**Comment by Miragecore** [comment]
* 확인 완료!
