### ISSUE TITLE
환결 설정에서 돌발 검지 센서 탭

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#16]
![image](https://cloud.githubusercontent.com/assets/1232645/18415762/c458da92-7838-11e6-93c0-cac37683f085.png)

* 에뮬레이터에서 위의 동작들과 연계될 필요가 있음
* 리셋
  * 에뮬레이터의 동작을 다시 시작
  * 또는 에뮬레이터상에서 디스플레이
* 센서 네트워크 설정
 * 에뮬레이터의 네트워크 설정을 변경함
 * 또는 에뮬레이터상에서 디스플레이
* 센서 시간
 * 에뮬레이터상의 시간을 변경
 * 또는 에뮬레이터상에서 디스플레이
* 레이더 제어
 * 에뮬레이터 상의 각 파라메터를 변경
 * 또는 에뮬레이터 상에서 디스플레이
* 레이더 전원
 * 또는 에뮬레이터상에서 디스플레이

**Comment by small-b** [comment]
>> 각각의 명령에 대하여 에뮬레이터에 디스플레이 되도록 수정하였습니다.

**Comment by Miragecore** [comment]
* 에뮬레이터에 디스플레이 기능은 확인 완료
* 이슈 #28 과 중복으로 인해 Close
