### ISSUE TITLE
소스 공유

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#17]
기존에 사용하던 SVN서버에 SmartIDS_GS라는 저장소를 추가해두었습니다.
거기를 이용하시면 될듯 합니다.

**Comment by small-b** [comment]
1. Commit 완료하였습니다.
2. 현장제어기 에뮬레이터는 SiteEmulator 프로젝트입니다.

**Comment by Miragecore** [comment]
확인했습니다. 수정시 바로 올려주시면 확인하겟습니다!
