### ISSUE TITLE
WatchDog 이벤트 이력창 수정

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#18]
![image](https://cloud.githubusercontent.com/assets/1232645/18421918/3d7e0424-78cf-11e6-93fb-d1ca03692890.png)

* 이벤트 유형 글자가 짤림
 * 특정 사이즈 이상으로 고정하거나 하여 짤리지 않도록 해야 할듯
* CCTV 버튼 삭제
 * 영상 저장 관련 기능이 없으므로 이 버튼은 안 보이게만 하면 될듯함.

**Comment by small-b** [comment]
>> 이벤트 유형 글자를 한글로 수정
>> CCTV 버튼 삭제함.

**Comment by Miragecore** [comment]
* 확인 완료
