### ISSUE TITLE
통계창 하단 기능

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#20]
![image](https://cloud.githubusercontent.com/assets/1232645/18422242/1c7e4f28-78d3-11e6-9801-403282410740.png)

* 기능하는 것이 좋겠지만 안한다면 제거
* 특히 Excel은 없으니 제거 하는게 좋을듯 합니다.

**Comment by small-b** [comment]
>> 제거합니다.

**Comment by Miragecore** [comment]
* 확인 완료
