### ISSUE TITLE
프로그램 명칭 변경

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#21]
기능 합의서상의 제품명이 돌발 상황 검지 시스템 V1.00으로 되어 있습니다.
때문에 프로그램 명칭을 돌발 상황 검지 시스템으로 변경하여야 할듯 합니다.

* 프로그램 명칭 변경 : 돌발 상황 검지 시스템 V1.00

**Comment by small-b** [comment]
>> WatchDog 대신에 "돌발 상황 검지 시스템" 으로 변경합니다.

**Comment by Miragecore** [comment]
* 확인 완료
