### ISSUE TITLE
지역 정보창에서 네트워크 설정 삭제

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#22]
![image](https://cloud.githubusercontent.com/assets/1232645/18431290/390cdad0-7917-11e6-8ed4-5c7dcab7b330.png)

* 의미없는 설정은 안보이는게 좋을 것으로 보입니다.

**Comment by small-b** [comment]
>> 이 화면은 실제로 현장제어기 연결정보를 설정하는 부분입니다.
(따라서, 지금은 에뮬레이터 IP 및 Port 를 입력합니다.)
