### ISSUE TITLE
레이더 리스트 상의 Search 기능

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#24]
![image](https://cloud.githubusercontent.com/assets/1232645/18431529/3b386544-7918-11e6-8744-f8a30638f62e.png)

* 위의 Search기능을 활용하기 위해 입력시 프로그램이 재시작되어버림.

**Comment by small-b** [comment]
>> 삭제합니다.

**Comment by Miragecore** [comment]
* 확인 완료
