### ISSUE TITLE
소스 재업 요청

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#27]
![image](https://cloud.githubusercontent.com/assets/1232645/18517513/8987ef4c-7ad7-11e6-80bd-36e08cfefc3f.png)

* SiteController 컴파일 할려니 위와 같은 에러가 납니다.
 * 이 앞전의 것은 컴파일이 잘 됩니다.
 * 프로젝트 파일이나 뭔가 누락된 것은 아닌가 합니다.
* WatchDog쪽은 컴파일에 문제가 없습니다.

**Comment by small-b** [comment]
재업하였습니다.
