### ISSUE TITLE
에뮬레이터의 현재 상태 디스플레이중 돌발 검지 센서 탭

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#28]
![image](https://cloud.githubusercontent.com/assets/1232645/18612663/d049d3f8-7d9a-11e6-909d-a6478ddce43c.png)

* 돌발검지 센서 탭이 위와 같이 검게 뜹니다.

**Comment by small-b** [comment]
WatchDog 에서 돌발검지센서를 제어하면 그 부분에 Console 처럼 적용되는 명령을 표시합니다.

**Comment by Miragecore** [comment]
* 확인 완료!
