### ISSUE TITLE
CCTV 명칭 수정이 안됨

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#29]
![image](https://cloud.githubusercontent.com/assets/1232645/18612719/87dbe4d8-7d9c-11e6-80fd-0245b7fc21a5.png)

* CCTV 수정 기능을 이용하여 명칭 수정시 CCTV명칭이 변경되지 않음

**Comment by small-b** [comment]
ㅡ,.ㅡ;;;;; 되는데용;;;;

**Comment by Miragecore** [comment]
음 제가 이상한가요;
수정하면 바로 반영이 안되고 프로그램을 재시작하면 수정이 되네요.
이건 천천히 하시죠. 
안되면 매뉴얼에 다시 시작하라고 하죠 뭐

**Comment by Miragecore** [comment]
음 바로 반영은 안되고 다시 클릭해서 활성화하면 반영이 되긴 하는군요

**Comment by Miragecore** [comment]
* 수정된 내용 확인
