### ISSUE TITLE
이동 차량 도시 기능에서 속도

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#3]
* 레이더 관제 > 검지 데이터 출력 > 이동 차량 도시 기능 관련
 * ID와 속도 등의 정보를 텍스트로 표시하는 기능으로 정의됨.
* 레이더뷰에서는 ID만 보임

**Comment by small-b** [comment]
레이더뷰에서 ID 우측 괄호 내에 속도 표시함.

**Comment by Miragecore** [comment]
현재 에뮬레이터로는 교통상황을 표현해주는 기능이 없어서 기능 확인 불가
