### ISSUE TITLE
전역 맵 전환 기능

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#30]
![image](https://cloud.githubusercontent.com/assets/1232645/18612912/da6c46b8-7da4-11e6-835f-8d4bc13e7ff4.png)

1. 위와 같이 레이더를 하나 더 추가후
2. 전역 맵의 노란 화살표를 이용하여 전역 맵 전환 시도
3. 전역 맵이 전환되지 않음.

#4 에서와 달리 레이더 추가시 프로그램 재시작하지 않고 레이더가 있을 시에 
전역맵의 전환을 확인하기 위한 테스트였으나 전환 기능이 동작하지 않습니다.

**Comment by small-b** [comment]
![image](https://cloud.githubusercontent.com/assets/22072776/18614650/b1415b60-7dcd-11e6-9c02-2fea46e1ccca.png)
그림과 같이 추가된 레이더를 모두 표시하도록 수정하였습니다.

**Comment by Miragecore** [comment]
확인 완료
