### ISSUE TITLE
이벤트 이력창에서 돌발 정보 자동 전송

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#31]
* CheckBox 기능 설명 좀 부탁드립니다.

**Comment by small-b** [comment]
이 부분은 RSE 와 관련된 것으로 이벤트 발생시, 자동으로 RSE에 이벤트 메시지를 전송할지 여부를 체크하는 것입니다.

**Comment by Miragecore** [comment]
* RSE는 현장 제어기와 관련된 기능이지 않은가요? WatchDog에서 동작하지 않는 기능인듯 합니다만?
* 그냥 안 보이는게 좋지 않을려나요?

**Comment by small-b** [comment]
수정하였습니다.

**Comment by Miragecore** [comment]
* 어떻게 수정하신건가요? 예는 계속 보이는데요?
