### ISSUE TITLE
이벤트 이력창과 팝업창의 알림 창을 표시하지 않음 동기화

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#32]
![image](https://cloud.githubusercontent.com/assets/1232645/18613130/c6e16b42-7dad-11e6-84bf-146f644dbd30.png)

* 팝업창에서 표시하지 않음을 Check하면 다음부터 표시되지 않습니다.
* 단 이력창의 표시하지 않음은 Check되어 있지 않습니다.
* 이력창의 표시하지 않음을 Check해도 팝업창은 보이지 않습니다.
*  이력창의 표시하지 않음을 UnCheck하면 팝업창이 보입니다.

결론
팝업창에서 팝업창을 안 보이게 했다가 다시 보이게 하고 싶으면, 이력창에서 표시하지 않음을 Check했다가 UnCheck하여야함.

**Comment by small-b** [comment]
수정하였습니다.

**Comment by Miragecore** [comment]
확인 완료
