### ISSUE TITLE
이벤트 팝업창의 정보가 짤려서 보이지 않음

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#33]
![image](https://cloud.githubusercontent.com/assets/1232645/18613153/7c72e1e8-7dae-11e6-8734-1950e1feab34.png)
 
* 위와 같이 지역의 정보가 짤려져 버립니다.
* 폰트를 확 줄여버리거나 창 키우면 될듯합니다!

**Comment by small-b** [comment]
수정하였습니다.

**Comment by Miragecore** [comment]
확인 완료
