### ISSUE TITLE
연결 상태바의 기능 설명 부탁드립니다.

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#34]
![image](https://cloud.githubusercontent.com/assets/1232645/18613470/af9d87fa-7db6-11e6-8e6a-d1369f425eac.png)

무슨 색일 때 뭐다 이런식으로 간단히 설명 부탁드립니다.

**Comment by small-b** [comment]
![image](https://cloud.githubusercontent.com/assets/22072776/18614476/2eea2a3c-7dca-11e6-8b02-bc464b54523e.png)
글로벌 레벨에서는 좌측에 초록색으로 표시되면 하위 현장제어기 중 최소 1개 이상 접속되었을 경우임.
![image](https://cloud.githubusercontent.com/assets/22072776/18614493/5f2efa4c-7dca-11e6-8cf9-f74205157c88.png)
현장제어기 레벨에서는 좌측 초록색으로 표시되면 해당 현장제어기와 연결됨을 나타냄
연결되지 않았을 경우, 회색으로 표시함.
![image](https://cloud.githubusercontent.com/assets/22072776/18614501/7c9f471c-7dca-11e6-830f-230683c8360f.png)
레이더 레벨에서는 평소 표시되지 않으나, setting 버튼 우측을 클릭하면 Tx, Rx 상태를 나타내는 램프가 표시됨(Rx 시 파란색 램프가 깜빡이고, Tx 시 붉은색 램프가 깜빡임)

**Comment by Miragecore** [comment]
* 제가 처음 올린 이미지를 보면 좌측에 하늘색 램프가 있어서 저건 뭔가요?

**Comment by small-b** [comment]
저건 그냥 마우스 클릭해서 선택된거 입니다.
