### ISSUE TITLE
광역, 지점, 레이더 생성시 명칭 없이 생성 가능

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#35]
![image](https://cloud.githubusercontent.com/assets/1232645/18613915/132fe602-7dbf-11e6-8965-4aa93876911a.png)

* 광역 그룹 명칭 없이 생성 가능
* 지점 그룹 명칭 없이 생성 가능
* 레이더 명칭 없이 생성 가능

**Comment by small-b** [comment]
수정하였습니다.

**Comment by Miragecore** [comment]
확인 완료
