### ISSUE TITLE
레이더 정보창 불필요 정보 삭제

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#36]
![image](https://cloud.githubusercontent.com/assets/1232645/18614426/848feba8-7dc9-11e6-80f1-adcf47829b4b.png)

* 불필요 정보 삭제
* 연계 장비 삭제
* 설치 위치는 현장 제어기에서 표현해주므로 삭제
* Visible만 없애주시죠!

**Comment by Miragecore** [comment]
![image](https://cloud.githubusercontent.com/assets/1232645/18614442/c73e4508-7dc9-11e6-810f-0dc34613731b.png)
* 매뉴얼에는 이런 그림이 올라갈 겁니다.

**Comment by small-b** [comment]
수정하였습니다.

**Comment by Miragecore** [comment]
확인 완료
