### ISSUE TITLE
레이더 추가후 재시작시 레이더 사라짐

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#4]
* 레이더 추가후 프로그램 재기동시 레이더가 없음
* 실험 방법
 1. 광역/ 지역 관리 기능을 이용 새로운 광역/ 지역 생성
 2. 레이더 추가
   * 레이더 등록은 명칭과 MAC 주소만 기입
 3. 프로그램 재시작

**Comment by small-b** [comment]
수정함.

**Comment by Miragecore** [comment]
* 지역 추가 후 레이더 추가
* 프로그램 재시작시 레이더가 앞서 추가하였던 레이더는 여전히 없습니다.
* 추가한 레이더에서 Setting 버튼을 누를 경우 Watch Dog이 재시작되어버립니다.

**Comment by small-b** [comment]
수정하였습니다.

**Comment by Miragecore** [comment]
확인 완료
