### ISSUE TITLE
사용자 기능만 활성화

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#43]
* Setting 기능을 안 보이게 변화시켜야 할듯 합니다.
설정 기능을 활용하게 둘 경우, 설정 변경에 따른 실제 변화도 확인이 가능해야 한다는
TTA측의 의견이 있었습니다.
그래서 차라리 접근이 불가능하도록(안보이게) 수정하는 것이 좋을 것 같습니다.

**Comment by small-b** [comment]
* 그럼, 에뮬레이터에서도 설정 표시되는 부분을 없에나요?

**Comment by Miragecore** [comment]
* 수정 확인
