### ISSUE TITLE
새로운 레이더 추가시 기존 레이더 사라짐

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#7]
* UI의 레이더 추가를 이용하여 레이더 추가시 기존의 레이더 사라짐

**Comment by small-b** [comment]
* 현장제어기(국지서버)와 레이더는 1:1 관계에 있으므로,
* 레이더를 2개 이상 추가시, 추가 금지 알림창을 띄우고 추가하지 못하게 함.

**Comment by Miragecore** [comment]
* 확인 완료
