### ISSUE TITLE
에뮬레이터의 돌발 발생 기능 필요

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#8]
* 기능 테스트시 사용할 도발 발생 기능 필요

**Comment by small-b** [comment]
* 구현 완료

**Comment by Miragecore** [comment]
![image](https://cloud.githubusercontent.com/assets/1232645/18421978/ec606e0a-78cf-11e6-9775-3cc6f967c56e.png)

* 어차피 이벤트가 일회성으로 발생할 것이라면 PushButton이 아니라 그냥 Button으로 한번 클릭만 되면 될듯함.
 * 이력이 필요하다면 텍스트박스 정도로 뭐 눌렀었다 정도 추가해주는 정도면 될듯합니다.
* 지정체 클릭시 WatchDog이 재실행되는 버그 발견

**Comment by small-b** [comment]
>> PushButton 으로 만든건 이벤트 발생/해지를 위해서 입니다.
>> 지정체 클릭시 WatchDog 오류는 수정하였습니다.
>> 기존 로그 재생은 시간이 좀 걸릴듯 합니다. 일단 보류하였음 합니다.

**Comment by Miragecore** [comment]
로그 재생 기능을 합쳐서 하나의 에뮬레이터로 만드는 것이 오래 걸릴 것 같으면 차라리 2개의 에뮬레이터를 만드는 것도 괜찮을 것 같습니다.
로그 재생 기능만 하는 에뮬레이터로요.
