### ISSUE TITLE
레이더 추가시 필수 항목 변경

### ISSUE THREAD

**Issue by Miragecore** [WorkForGS/ToBeNice#9]
* 레이더 추가시 현재 필수 항목으로 MAC 주소를 사용
* MAC 보다는 IP를 사용하는 것이 더 좋지 않을까 생각함.

**Comment by small-b** [comment]
레이더 추가시 MAC 주소 기본값이 0.0.0.0.0.0 을 가지도록 수정

**Comment by Miragecore** [comment]
* 음 제가 보고 있는게 최신이 아닐수도 있을듯한 느낌이 드는군요!

**Comment by Miragecore** [comment]
* 확인 완료
